// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"database/sql"
	"time"
)

type Chat struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	IsMeeting bool   `json:"is_meeting"`
	IsAntibot bool   `json:"is_antibot"`
}

type ChatMeeting struct {
	ChatID    int64 `json:"chat_id"`
	MeetingID int64 `json:"meeting_id"`
	MessageID int64 `json:"message_id"`
}

type Meeting struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Status      string         `json:"status"`
	PublishedAt sql.NullTime   `json:"published_at"`
	ClosedAt    sql.NullTime   `json:"closed_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Message     sql.NullString `json:"message"`
	Max         sql.NullInt64  `json:"max"`
	Cost        sql.NullInt64  `json:"cost"`
	TypePay     string         `json:"type_pay"`
	OwnerID     int64          `json:"owner_id"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	IsOwner  bool   `json:"is_owner"`
}

type UserMeeting struct {
	UserID    int64         `json:"user_id"`
	MeetingID int64         `json:"meeting_id"`
	Count     sql.NullInt64 `json:"count"`
	Status    string        `json:"status"`
}
