// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	IsMeeting bool   `json:"is_meeting"`
	IsAntibot bool   `json:"is_antibot"`
	IsPrivate bool   `json:"is_private"`
}

type ChatMeeting struct {
	ChatID    int64 `json:"chat_id"`
	MeetingID int64 `json:"meeting_id"`
	MessageID int64 `json:"message_id"`
}

type Meeting struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Message     pgtype.Text        `json:"message"`
	Max         pgtype.Int8        `json:"max"`
	Cost        pgtype.Int8        `json:"cost"`
	TypePay     string             `json:"type_pay"`
	OwnerID     int64              `json:"owner_id"`
}

type User struct {
	ID       int64       `json:"id"`
	Nickname pgtype.Text `json:"nickname"`
	Username string      `json:"username"`
	IsOwner  bool        `json:"is_owner"`
}

type UserMeeting struct {
	UserID    int64       `json:"user_id"`
	MeetingID int64       `json:"meeting_id"`
	Count     pgtype.Int8 `json:"count"`
	Status    string      `json:"status"`
}
