// Code generated by options-gen v0.51.0. DO NOT EDIT.

package logger

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	level string,
	env string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.level = level
	o.env = env

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithProductionMode(opt bool) OptOptionsSetter {
	return func(o *Options) { o.productionMode = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("level", _validate_Options_level(o)))
	errs.Add(errors461e464ebed9.NewValidationError("env", _validate_Options_env(o)))
	return errs.AsError()
}

func _validate_Options_level(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.level, "required,oneof=debug info warn error"); err != nil {
		return fmt461e464ebed9.Errorf("field `level` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_env(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.env, "required,oneof=local dev prod"); err != nil {
		return fmt461e464ebed9.Errorf("field `env` did not pass the test: %w", err)
	}
	return nil
}
