server:
  env: local # prod dev local

log:
  level: 'DEBUG'

telegram:
  token: ""
  webhook: "bot123456"
  public_url: "https://yourdomain.com"
  listen: ":8080"
  use_webhook: false

PG:
  host: localhost
  port: 5432
  user: default
  password: secret
  scheme: public
  db: meetings