// Code generated by options-gen v0.51.0. DO NOT EDIT.

package store

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptSQLiteOptionsSetter func(o *SQLiteOptions)

func NewSQLiteOptions(
	path string,
	options ...OptSQLiteOptionsSetter,
) SQLiteOptions {
	var o SQLiteOptions

	// Setting defaults from field tag (if present)

	o.path = path

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithIsDebug(opt bool) OptSQLiteOptionsSetter {
	return func(o *SQLiteOptions) { o.isDebug = opt }
}

func (o *SQLiteOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("path", _validate_SQLiteOptions_path(o)))
	return errs.AsError()
}

func _validate_SQLiteOptions_path(o *SQLiteOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.path, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `path` did not pass the test: %w", err)
	}
	return nil
}
